#define MORTARS_VERSION       0.5
#define MORTARS_VERSION_STR   #MORTARS_VERSION
#define MORTARS_LOG_HEADER    " [MOR]: "

#define MORTARS_DANGER_CLOSE_RADIUS        75
#define MORTARS_SPAWN_HEIGHT_DEFAULT       1000
#define MORTARS_DROP_SPEED_DEFAULT         -10
#define MORTARS_CLASSNAME_DEFAULT          "Sh_82mm_AMOS"

#define MORTARS_DEBUG_MARKER_COLOUR   "ColorGreen"
#define MORTARS_DEBUG_MARKER_BRUSH    "Border"